### ISSUE TITLE
ERROR: KeyError: 'LocalAddress' ?  

### ISSUE THREAD

**Issue by DrStein99** [rickyphewitt/emby-skill#65]
"CHECK EMBY" returns an error.  

Configured via the web admin in mycroft.  Running piCroft on Raspberry 3.  Emby server functions correctly, no problem there.  

Not sure how to troubleshoot this, debug.  Please advise.

```
 16:47:14.879 | INFO     |   674 | Emby | {'utterance': 'check emby', 'utterances': ['check emby']}
 16:47:22.511 | ERROR    |   674 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:923 | An error occurred while processing a request in Emby
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/emby.rickyphewitt/__init__.py", line 69, in handle_diagnostic
    self.speak_dialog('diag_public_info_success', info)
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1227, in speak_dialog
    self.dialog_renderer.render(key, data),
  File "/home/pi/mycroft-core/mycroft/dialog/dialog.py", line 110, in render
    line = line.format(**context)
KeyError: 'LocalAddress'
```

**Comment by DrStein99** [comment]
Nevermind.  For reasons unknown, "MSM INSTALL https://github.com/rickyphewitt/emby-skill" managed to install some copy of the code that did not match the main branch.  Not sure why this happened to me, but it did.
